# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-08 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_id',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
